import { Hero } from "@/sections";
import { HomeProps } from "@/typescript/interfaces/pages";
import dynamic from "next/dynamic";
import Head from "next/head";
import React from "react";
const Services = dynamic(() => import("@/sections/Services"), { suspense: true });

const Home: React.FC<HomeProps> = () => {
  return (
    <main className="home">
      <Head>
        <title>Ultra Tim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/NM.png" />
      </Head>
      <Hero
        title="Empowering IT projects to success"
        subtitle="Utilizing my skills in project management and programming to drive successful results by effective planning and executing projects, delivering on deadlines and goals, and developing customized solutions through programming."
        image="/images/office.webp"
      />
      {/* <Suspense fallback={<h2>Loading...</h2>}>
        <Services data={services} />
      </Suspense> */}
    </main>
  );
};
export default Home;
