import Hero from "@/sections/Hero";
import { HomeProps } from "@/typescript/interfaces/pages";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import dynamic from "next/dynamic";
import Head from "next/head";
import React, { Suspense } from "react";
import background from "../../public/images/hero.jpg";
import data from "../../translationKeys.json";
const Services = dynamic(() => import("@/sections/Services"), { suspense: true });
const About = dynamic(() => import("@/sections/About"), { suspense: true });
const Gallery = dynamic(() => import("@/sections/Gallery"), { suspense: true });

export const getStaticProps = async ({ locale }) => {
  const primaryServices = await data.services.primary;
  const secondaryServices = await data.services.secondary;
  return {
    props: {
      ...(await serverSideTranslations(locale, ["standard"])),
      primaryServices,
      secondaryServices,
    },
  };
};

const Home: React.FC<HomeProps> = ({ primaryServices, secondaryServices }) => {
  const { t } = useTranslation();
  return (
    <>
      <Head>
        <title>Ultra Tim S</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/NM.png" />
      </Head>
      <main className="home">
        <Hero
          title={
            <h1>
              {t("standard:Kontakt")} <span>S</span>
            </h1>
          }
          subtitle="Naša firma je specijalizovana za pružanje usluga selidbe, transporta, pakovanja i gradjevinskih usluga. Svojim klijentima nudimo najpovoljnije cene uz najviši nivo profesionalizma i pažljivog rukovanja sa njihovim stvarima ili projektima. Naš tim se sastoji od stručnih i iskusnih radnika koji su posvećeni da svaki posao obave sa maksimalnom efikasnošću i pažnjom prema klijentima."
          image={background.src}
        />
        <Suspense fallback="">
          <About />
        </Suspense>
        <Suspense fallback="">
          <Services data={primaryServices} type="primary" />
        </Suspense>
        <Suspense fallback="">
          <Services data={secondaryServices} type="secondary" />
        </Suspense>
        <Suspense fallback="">
          <Gallery />
        </Suspense>
      </main>
    </>
  );
};
export default Home;
